GP-151: Dynamic Fields on ManageCDP page
Tapera-Finance/gard.money pull request #14
Opened 2022-06-15 02:23 UTC by esyeng

Changes:
- Patches NaN error for maxGard on MAIN
- Updates logic in WrappedSummary.jsx to cleanly compute both ratio and liquidation price
- Slight formatting adjustments (render modal content top down, add margin to specifics values)

2022-06-15 14:54 UTC, mccabe-david requested changes
Looks almost finished! Next time please let me know if you haven't touched the styling!

2022-06-15 14:54 UTC, mccabe-david commented on src/components/WrappedSummary.jsx
> +                      <SpecificsValue>{'0.001 Algos'}</SpecificsValue>
This value isn't static. It needs to be computed using calcDevFees from cdp.js

2022-06-15 14:54 UTC, mccabe-david commented on src/components/WrappedSummary.jsx
> +                      <SpecificsValue>{
The position of the elements on the righthand side of the transaction summary are not as they are currently. Please figure out a way to right-align them.

2022-06-15 14:54 UTC, mccabe-david commented on src/components/WrappedSummary.jsx
> +                      <SpecificsValue>{
![current_alignment](https://user-images.githubusercontent.com/43038510/173858191-07569254-c810-4a72-a1dc-2654ea39e564.PNG)
See here for comparison. This happens in both add_collateral and mint

2022-06-16 19:21 UTC, mccabe-david commented
As soon as the values are aligned properly on the right-hand side, we're good to merge!

2022-06-16 19:40 UTC, esyeng commented
aligning those now, will pull main once more then should be good to go!

2022-06-16 22:27 UTC, esyeng commented
@mccabe-david requesting eyes on this once more :) nothing is broken, things are aligned, dark mode works, the kids are alright

2022-06-17 16:45 UTC, mccabe-david commented
> @mccabe-david requesting eyes on this once more :) nothing is broken, things are aligned, dark mode works, the kids are alright (aka the Child component)

Glad the kids are alright lol

2022-06-17 16:45 UTC, merged