[GP-137] - Opt in to assets
Tapera-Finance/gard.money pull request #6
Opened 2022-06-07 16:53 UTC by esyeng

Ensure users are opted into GARD, GAIN, and GARDIAN on creating their first CDP
Files changed:

- transactions/ids.js
- transactions/cdp.js
- .prettierrc.json

NOTE: some unnecessary changes to spacing and line breaks were introduced via prettier - this will be fixed in later task

2022-06-07 16:58 UTC, esyeng commented
@mccabe-david the changes to look at are two new functions verifyOptIn and createOptInTxn, right above openCDP, and calls for them in lines 300 - 402. need to fix the formatter as it obscures what was changed very annoyingly

2022-06-07 20:28 UTC, mccabe-david requested changes
Overall, the logic looks solid! Just a few edge cases to take care of. This PR will help us a lot!

2022-06-07 20:28 UTC, mccabe-david commented on src/transactions/cdp.js
> +  let optedInGard = verifyOptIn(info, gardID);
Could this be simplified by replacing all instances of "optedIn" with "optedInGard"? That's what optedIn referred to initially

2022-06-07 20:28 UTC, mccabe-david commented on src/transactions/cdp.js
> +      100000 * (info["assets"].length + 1) +
This error catch should change to +3 (for 3 potential additional opt ins), and the same goes for the Maximum Deposit alert below. Ideally, we should do this alert later. See my comments on what the "start" variable represents

2022-06-07 20:28 UTC, mccabe-david commented on src/transactions/cdp.js
> +      100000 * (info["assets"].length + 1) +
Maybe this should be +4 come to think of it. I think when this was initially added we forgot to account for opt-ins altogether,

2022-06-07 20:28 UTC, mccabe-david commented on src/transactions/cdp.js
> +  let start = 0;
"start" should equal the number of tokens that need to be opted into. Furthermore, all signed txns of the form stxns[1+k].blob for k=1,2,...,start (do no pushes if start=0) should be pushed to the r1_stxns array.

2022-06-08 18:17 UTC, esyeng commented
@mccabe-david updated to address comments

2022-06-08 19:50 UTC, mccabe-david approved these changes
I think everything should work now, but I'll run a few tests before merging

2022-06-08 19:50 UTC, mccabe-david commented on src/transactions/cdp.js
> +  }
There's still an issue here for users who have opted-in to GARD and GAIN, but not GARDIAN

2022-06-08 19:55 UTC, esyeng commented on src/transactions/cdp.js
> +    start += 1;
ah yeah this makes more sense, thanks for the adjustment

2022-06-08 19:58 UTC, merged