V2 swap
Tapera-Finance/gard.money pull request #64
Opened 2022-08-10 23:46 UTC by esyeng

1st Pass @ V2 Swap:

New Components: 

- SwapDetails.jsx (used to be SwapContent)
- SwapContainer.jsx (Container for "Actions" page, ie Swap, Pool, Stake etc)
- Effect.jsx
- ToolTip.jsx
- ExchangeFields.jsx
- Input,jsx
- Select.jsx

Change Summary:
- reworked input functionality and implemented bilaterally editable, asset agnostic inputs
- reworked swap.js logic to target pools based on id and flags based on direction rather than hardcoded 'from this to that'
- created reusable new components to replace page specific features
- extended styling and structured page to v2 design

2022-08-11 00:07 UTC, esyeng commented
TODO:
- review preview effect calculations, fix discrepancies
- make slippage tolerance editable
- add slider
- TBD add other asset pools and asset pairings

2022-08-11 17:05 UTC, mccabe-david requested changes
Overall looks good, but I think some things should be changed before merging. I will provide more info on bugs I'm experiencing shortly

2022-08-11 17:05 UTC, mccabe-david commented on src/transactions/swap.js
> +  let txns = Array.isArray(optTxn) ? optTxn.concat([txn1, txn2]) : [txn1, txn2];
Has this been tested with a wallet that hasn't opted into the toAsset? code on the sides of the " : " should be swapped

2022-08-11 17:05 UTC, mccabe-david commented on src/transactions/swap.js
> +      formattedAmount / 1e6 +
We should fetch the decimals of each asset instead of hard-coding 6 here. I suspect we already have a asset info call somewhere.

2022-08-11 17:05 UTC, mccabe-david commented on src/transactions/swap.js
> +      fromAsset.name.toLocaleUpperCase(),
There should be a spaced between the value and the name, too.

2022-08-11 17:05 UTC, mccabe-david commented on src/transactions/swap.js
> +  updateDBWebActions(8, null, minimum, -fromAmt, 0, 1, 3000);
Now would be a good time to record the pair as well. I believe there is a space allotted for it in the DB Schema, but double check with Minh

2022-08-11 17:12 UTC, esyeng commented on src/components/swap/SwapDetails.jsx
> +    let ratio = await algoGardRatio();
this is from the old swap I realize, will remove since the exchange rate is calculated by the assets in the pool and not from this block

2022-08-16 14:02 UTC, ElianaTroper commented
Some feedback focused on usability:

- The drop down asset selector should also appear when clicking on the arrow next to the asset name too
- Slippage tolerance should be a modifiable parameter
- Exchange rate should display (as a non-zero value) before adjusting either asset total
- We don't need two price impacts (they will always be opposites of each other)
- Executing a swap where you send more assets than you have should not be allowed

2022-08-22 12:05 UTC, ElianaTroper commented
Looking good, some feedback:

- Swapping slippage tolerance should affect minimum received
- Slippage tolerance would look better as a drop down
- tooltips should use a help cursor (see https://developer.mozilla.org/en-US/docs/Web/CSS/cursor)
- Asset would look better centered: ![image](https://user-images.githubusercontent.com/35941672/185916045-2534f494-3fde-41e5-a727-2ed2cc02a8fa.png)
- Selection bar needs some work: 
![image](https://user-images.githubusercontent.com/35941672/185917006-3bbdf3f8-acac-49d2-b079-a6d467839ffb.png)

Discussion/don't act on this yet:
- Asset A/B total fields are not totally accurate (especially for GARD) since that's the maximum possible total. Circulating supply would be a better metric to show.

I want to merge this into v2 as is, but you should continue work.

2022-08-25 15:23 UTC, merged